name: foodie
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^8.5.0
  flare_flutter: ^1.5.9
  flare_splash_screen: ^2.1.3
  cloud_firestore:
  firebase_auth:
  bloc_pattern: ^2.4.0+2
  rxdart: ^0.22.2
  grouped_buttons: ^1.0.4
  splashscreen: ^1.2.0
  cupertino_icons: ^0.1.2
  scrollable_bottom_sheet: ^0.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:

      - assets/images/





  fonts:
      - family: Montserrat
        fonts:
          - asset: assets/fonts/Montserrat-Black.ttf
          - asset: assets/fonts/Montserrat-Bold.ttf
          - asset: assets/fonts/Montserrat-ExtraBold.ttf
          - asset: assets/fonts/Montserrat-ExtraLight.ttf
          - asset: assets/fonts/Montserrat-Light.ttf
          - asset: assets/fonts/Montserrat-Medium.ttf
          - asset: assets/fonts/Montserrat-Regular.ttf
          - asset: assets/fonts/Montserrat-SemiBold.ttf
          - asset: assets/fonts/Montserrat-Thin.ttf


      - family: Quicksand
        fonts:
          - asset: assets/fonts/Quicksand-Regular.ttf
          - asset: assets/fonts/Quicksand-Bold.ttf
          - asset: assets/fonts/Quicksand-Medium.ttf
          - asset: assets/fonts/Quicksand-SemiBold.ttf

